ServiceApiKeyDataTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ServiceApiKeyDataTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: apiKeyName
        AttributeType: S
      - AttributeName: accessKeyName
        AttributeType: S
    KeySchema:
      - AttributeName: apiKeyName
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: accessKeyIndex
        KeySchema:
          - AttributeName: accessKeyName
            KeyType: HASH
        Projection:
          ProjectionType: INCLUDE
          NonKeyAttributes:
            - accessKeyName
            - companyName
            - userName
            - orgName
            - keyState
